# Generated by Django 5.2.7 on 2026-03-25 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartidaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=200)),
                ('proceso', models.CharField(max_length=200)),
                ('operacion', models.CharField(max_length=300)),
                ('producto_intermedio', models.CharField(blank=True, max_length=300)),
                ('indicador', models.TextField(blank=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='Sin descripción', max_length=255)),
                ('unidad_medida', models.CharField(default='Sin unidad', max_length=50)),
                ('partida', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogos.partidapresupuestaria')),
            ],
        ),
    ]
