# Generated by Django 5.2.7 on 2026-04-07 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(default='', max_length=255)),
                ('unidad_medida', models.CharField(default='Sin unidad', max_length=50)),
                ('partida', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['partida'], name='catalogos_i_partida_329334_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperacionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=200)),
                ('proceso', models.CharField(max_length=200)),
                ('operacion', models.CharField(max_length=300)),
                ('producto_intermedio', models.CharField(blank=True, max_length=300)),
                ('indicador', models.TextField(blank=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.direccion')),
            ],
        ),
    ]
