# Generated by Django 5.2.7 on 2026-03-26 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.CharField(max_length=50)),
                ('nombre_item', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_maestro', to='catalogos.partidapresupuestaria')),
            ],
        ),
        migrations.AddField(
            model_name='itemcatalogo',
            name='item_maestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='catalogos.itemmaestro'),
        ),
        migrations.AddIndex(
            model_name='itemcatalogo',
            index=models.Index(fields=['partida'], name='catalogos_i_partida_a0b628_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcatalogo',
            index=models.Index(fields=['item_maestro'], name='catalogos_i_item_ma_bb055f_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmaestro',
            index=models.Index(fields=['partida', 'codigo_item'], name='catalogos_i_partida_92c906_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemmaestro',
            constraint=models.UniqueConstraint(fields=('partida', 'codigo_item'), name='uq_itemmaestro_partida_codigo'),
        ),
    ]
