# Generated by Django 5.2.7 on 2026-03-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_itemmaestro_itemcatalogo_item_maestro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcatalogo',
            name='item_maestro',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='itemcatalogo',
                    name='catalogos_i_item_ma_bb055f_idx',
                ),
            ],
        ),
        migrations.DeleteModel(
            name='ItemMaestro',
        ),
    ]
