# Generated by Django 5.2.7 on 2026-03-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_remove_itemcatalogo_nro'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='itemcatalogo',
            new_name='catalogos_i_partida_329334_idx',
            old_name='catalogos_i_partida_a0b628_idx',
        ),
        migrations.AlterField(
            model_name='itemcatalogo',
            name='detalle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
