# Generated by Django 4.2.7 on 2025-11-02 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('facultad', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['facultad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('categoria', models.CharField(choices=[('catedratico', 'Catedrático'), ('adjunto', 'Adjunto'), ('asistente', 'Asistente')], max_length=20)),
                ('dedicacion', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('horario', 'Horario'), ('medio_tiempo', 'Medio Tiempo')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='FondoTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('asignatura', models.CharField(max_length=200)),
                ('semanas_año', models.IntegerField(default=52)),
                ('horas_semana', models.IntegerField(default=40)),
                ('horas_vacacion', models.IntegerField(default=120)),
                ('horas_feriados', models.IntegerField(default=128)),
                ('contrato_horas', models.IntegerField(default=2080)),
                ('clases_aula_horas', models.IntegerField(default=240)),
                ('funciones_sustantivas_horas', models.IntegerField(default=1124)),
                ('horas_efectivas', models.IntegerField(default=1832)),
                ('total_asignado', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('validado', 'Validado'), ('aprobado', 'Aprobado')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fondos_tiempo', to='fondos.carrera')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fondos_tiempo', to='fondos.docente')),
            ],
            options={
                'verbose_name': 'Fondo de Tiempo',
                'verbose_name_plural': 'Fondos de Tiempo',
                'ordering': ['-gestion', 'docente'],
                'unique_together': {('docente', 'gestion', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaFuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('docente', 'Docente'), ('investigacion', 'Investigación'), ('extension', 'Extensión e Interacción Social'), ('asesorias', 'Asesorías y Tutorías'), ('tribunales', 'Tribunales'), ('administrativo', 'Administrativo'), ('vida_universitaria', 'Vida Universitaria')], max_length=30)),
                ('total_horas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fondo_tiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='fondos.fondotiempo')),
            ],
            options={
                'verbose_name': 'Categoría de Función',
                'verbose_name_plural': 'Categorías de Funciones',
                'ordering': ['fondo_tiempo', 'tipo'],
                'unique_together': {('fondo_tiempo', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=300)),
                ('horas_semana', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('horas_año', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('evidencias', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='fondos.categoriafuncion')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['categoria', 'orden', 'id'],
            },
        ),
    ]
