# Generated by Django 5.2.7 on 2025-11-03 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('director', 'Director de Carrera'), ('docente', 'Docente')], default='docente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(blank=True, help_text='Carrera asignada (para directores)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fondos.carrera')),
                ('docente', models.OneToOneField(blank=True, help_text='Relacionar con el registro de Docente si el usuario es docente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='fondos.docente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
