# Generated by Django 5.2.7 on 2025-11-18 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0005_calendarioacademico_fondotiempo_calendario_academico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('investigacion', 'Investigación'), ('extension', 'Extensión Universitaria'), ('interaccion', 'Interacción Social')], max_length=20)),
                ('antecedentes', models.TextField(help_text='Antecedentes del proyecto (Art. 16)')),
                ('justificacion', models.TextField(help_text='Justificación del proyecto (Art. 16)')),
                ('objetivos', models.TextField(help_text='Objetivos del proyecto (Art. 16)')),
                ('problema', models.TextField(blank=True, help_text='Problema que aborda el proyecto (Art. 16)')),
                ('cronograma', models.JSONField(blank=True, default=dict, help_text='Cronograma: lugar, fecha, hora de realización')),
                ('es_curso_seminario', models.BooleanField(default=False, help_text='Indica si es curso, seminario o capacitación')),
                ('bibliografia', models.TextField(blank=True, help_text='Bibliografía básica (Art. 17.1)')),
                ('grupo_objetivo', models.CharField(blank=True, help_text='Identificación del grupo a capacitar (Art. 17.3)', max_length=200)),
                ('requisitos_asistencia', models.TextField(blank=True, help_text='Requisitos de asistencia (Art. 17.4)')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Híbrida')], default='presencial', help_text='Presencial o virtual (Art. 17.5)', max_length=20)),
                ('frecuencia', models.CharField(blank=True, help_text='Frecuencia semanal/mensual (Art. 17.6)', max_length=100)),
                ('horas_diarias', models.IntegerField(blank=True, help_text='Horas diarias (Art. 17.6)', null=True)),
                ('material_didactico', models.TextField(blank=True, help_text='Material didáctico a utilizar (Art. 17.7)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('presentado', 'Presentado'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En Ejecución'), ('finalizado', 'Finalizado'), ('observado', 'Con Observaciones')], default='borrador', max_length=20)),
                ('fecha_presentacion', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='fondos.categoriafuncion')),
                ('fondo_tiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='fondos.fondotiempo')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece esta actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='fondos.proyecto'),
        ),
    ]
