# Generated by Django 5.2.7 on 2025-11-18 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0006_proyecto_actividad_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('parcial', 'Informe Parcial'), ('final', 'Informe Final de Gestión')], max_length=10)),
                ('fecha_elaboracion', models.DateField(auto_now_add=True)),
                ('resumen_ejecutivo', models.TextField(help_text='Resumen de las actividades realizadas')),
                ('actividades_realizadas', models.TextField(help_text='Detalle de actividades ejecutadas')),
                ('resultados', models.TextField(help_text='Resultados obtenidos')),
                ('evidencias', models.TextField(blank=True, help_text='Evidencias de cumplimiento (URLs, descripciones)')),
                ('observaciones', models.TextField(blank=True)),
                ('cumplimiento', models.CharField(blank=True, choices=[('cumplido', 'Cumplido'), ('parcial', 'Cumplimiento Parcial'), ('incumplido', 'Incumplido')], help_text='Evaluación del cumplimiento (llenado por Director)', max_length=15)),
                ('evaluacion_director', models.TextField(blank=True, help_text='Evaluación del Director de Carrera')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True)),
                ('archivo_url', models.URLField(blank=True, help_text='URL del archivo del informe (PDF, Drive, etc.)')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('elaborado_por', models.ForeignKey(help_text='Docente que elabora el informe', on_delete=django.db.models.deletion.PROTECT, related_name='informes_elaborados', to=settings.AUTH_USER_MODEL)),
                ('evaluado_por', models.ForeignKey(blank=True, help_text='Director que evaluó el informe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_evaluados', to=settings.AUTH_USER_MODEL)),
                ('fondo_tiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='fondos.fondotiempo')),
            ],
            options={
                'verbose_name': 'Informe de Fondo',
                'verbose_name_plural': 'Informes de Fondos',
                'ordering': ['-fecha_elaboracion'],
            },
        ),
    ]
