# Generated by Django 5.2.7 on 2025-11-18 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0008_observacionfondo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='informefondo',
            name='archivo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='cumplimiento',
            field=models.CharField(blank=True, choices=[('cumplido', 'Cumplido'), ('parcial', 'Cumplimiento Parcial'), ('incumplido', 'Incumplido')], max_length=15),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='elaborado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_elaborados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='evaluacion_director',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='evaluado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_evaluados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='evidencias',
            field=models.TextField(blank=True, help_text='Evidencias de cumplimiento'),
        ),
        migrations.AlterField(
            model_name='observacionfondo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observacionfondo',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observacionfondo',
            name='fondo_tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_detalladas', to='fondos.fondotiempo'),
        ),
        migrations.AlterField(
            model_name='observacionfondo',
            name='observacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='observacionfondo',
            name='respondida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_respondidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observacionfondo',
            name='respuesta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='observacionfondo',
            name='resuelta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='observacionfondo',
            name='rol',
            field=models.CharField(choices=[('director', 'Director de Carrera'), ('decano', 'Decano'), ('vicerrector', 'Vicerrector de Grado'), ('planificacion', 'Dirección de Planificación Académica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fondos.carrera'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='docente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='fondos.docente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='bibliografia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cronograma',
            field=models.JSONField(blank=True, default=dict, help_text='Cronograma: lugar, fecha, hora'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='es_curso_seminario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='grupo_objetivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='horas_diarias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='material_didactico',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Híbrida')], default='presencial', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='requisitos_asistencia',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='HistorialFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_cambio', models.CharField(choices=[('creacion', 'Creación'), ('edicion', 'Edición'), ('presentacion', 'Presentación'), ('aprobacion', 'Aprobación'), ('observacion', 'Observación'), ('rechazo', 'Rechazo'), ('finalizacion', 'Finalización'), ('archivado', 'Archivado')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30)),
                ('datos_cambio', models.JSONField(blank=True, default=dict, help_text='Snapshot de los datos modificados')),
                ('fondo_tiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='fondos.fondotiempo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'ordering': ['-fecha'],
            },
        ),
    ]
