# Generated by Django 5.2.7 on 2025-11-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0009_alter_informefondo_archivo_url_and_more'),
    ]

    operations = [
        # No-op: el campo `total_asignado` ya no forma parte del estado base
        # actual del modelo. Mantener esta migracion vacia evita fallos al
        # reconstruir el estado historico en entornos actualizados.
    ]
