# Generated by Django 5.2.7 on 2025-11-24 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0010_remove_fondotiempo_total_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observacionfondo',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Observación', 'verbose_name_plural': 'Observaciones'},
        ),
        migrations.RenameField(
            model_name='observacionfondo',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='observacionfondo',
            old_name='fecha_respuesta',
            new_name='fecha_resolucion',
        ),
        migrations.RemoveField(
            model_name='observacionfondo',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='observacionfondo',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='observacionfondo',
            name='respondida_por',
        ),
        migrations.RemoveField(
            model_name='observacionfondo',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='observacionfondo',
            name='rol',
        ),
        migrations.AddField(
            model_name='observacionfondo',
            name='resuelta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MensajeObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_admin', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_observacion', to=settings.AUTH_USER_MODEL)),
                ('observacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='fondos.observacionfondo')),
            ],
            options={
                'verbose_name': 'Mensaje de Observación',
                'verbose_name_plural': 'Mensajes de Observación',
                'ordering': ['fecha'],
            },
        ),
    ]
