# Generated by Django 5.2.7 on 2025-11-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0011_alter_observacionfondo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
