# Generated by Django 5.2.7 on 2025-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0012_docente_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondotiempo',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fondotiempo',
            name='fecha_informe',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fondotiempo',
            name='fecha_inicio_ejecucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
