# Generated by Django 5.2.7 on 2025-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0013_fondotiempo_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefondo',
            name='logros',
            field=models.TextField(default='', help_text='Logros alcanzados'),
            preserve_default=False,
        ),
    ]
