# Generated by Django 5.2.7 on 2026-02-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0017_alter_fondotiempo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='horas_contrato_semanales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Horas semanales de contrato para dedicación 'Horario'", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='horas_efectivas',
            field=models.DecimalField(decimal_places=2, default=1832.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='horas_feriados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='horas_semana',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas semanales del docente según su dedicación', max_digits=5),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='semanas_año',
            field=models.DecimalField(decimal_places=1, default=45.8, help_text='Número de semanas efectivas del año para cálculo de horas anuales', max_digits=4),
        ),
    ]
