# Generated by Django 5.2.7 on 2026-02-13 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0019_remove_informefondo_archivo_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('docente', 'Docente'), ('investigacion', 'Investigación'), ('extension', 'Extensión e Interacción Social'), ('asesorias', 'Asesorías y Tutorías'), ('tribunales', 'Tribunales'), ('administrativo', 'Administrativo'), ('vida_universitaria', 'Vida Universitaria')], max_length=30)),
                ('titulo_actividad', models.CharField(help_text='Ej: "Mat. Cálculo I", "Proyecto Riego", "Dirección de Carrera"', max_length=200)),
                ('horas', models.PositiveIntegerField(help_text='Cantidad de horas anuales asignadas para esta actividad.')),
                ('documento_respaldo', models.CharField(blank=True, help_text='Opcional. Ej: "Memo #123", "Res. HCF #456/2024"', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carga Horaria',
                'verbose_name_plural': 'Cargas Horarias',
                'ordering': ['-calendario__gestion', 'docente', 'categoria'],
            },
        ),
        migrations.AlterField(
            model_name='docente',
            name='horas_contrato_semanales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ATENCIÓN: Ingrese la carga SEMANAL. (Ejemplo: Si el contrato es de 40 hrs/mes, ingrese 10)', max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='fondotiempo',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_fondo', 'semestral')), fields=('docente', 'gestion', 'periodo', 'asignatura'), name='unique_semestral_fondo'),
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='calendario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_horarias', to='fondos.calendarioacademico'),
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_horarias', to='fondos.docente'),
        ),
        migrations.AlterUniqueTogether(
            name='cargahoraria',
            unique_together={('docente', 'calendario', 'categoria', 'titulo_actividad')},
        ),
    ]
