# Generated by Django 6.0.2 on 2026-02-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0020_cargahoraria_alter_docente_horas_contrato_semanales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='evidencias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
