# Generated by Django 6.0.2 on 2026-02-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0021_alter_actividad_evidencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='evidencias',
            field=models.TextField(blank=True, default=''),
        ),
    ]
