# Generated by Django 5.2.7 on 2026-02-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0022_alter_actividad_evidencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='dias_vacacion',
            field=models.IntegerField(default=15, help_text='Días de vacación correspondientes según antigüedad'),
        ),
        migrations.AddField(
            model_name='docente',
            name='horas_feriados_gestion',
            field=models.IntegerField(default=128, help_text='Total de horas de feriados en la gestión académica'),
        ),
    ]
