# Generated by Django 6.0.2 on 2026-02-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0024_perfilusuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=20)),
                ('semestre', models.IntegerField()),
                ('horas_teoricas', models.IntegerField(default=0)),
                ('horas_practicas', models.IntegerField(default=0)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='fondos.carrera')),
            ],
        ),
    ]
