# Generated by Django 6.0.2 on 2026-02-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0025_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='sigla',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
