# Generated by Django 6.0.2 on 2026-02-20 18:19

import fondos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0026_alter_materia_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='archivo_evidencia',
            field=models.FileField(blank=True, help_text='Prueba visual (Imagen/PDF)', null=True, upload_to=fondos.models.evidencia_upload_path),
        ),
    ]
