# Generated by Django 6.0.2 on 2026-02-20 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0027_actividad_archivo_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de ingreso a la institución para cálculo de antigüedad'),
        ),
    ]
