# Generated by Django 5.2.7 on 2026-03-19 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0029_perfilusuario_foto_cifrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoVacacionesGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField(help_text='Año/Gestión académica', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('dias_disponibles', models.IntegerField(help_text='Días de vacación disponibles para esta gestión')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_vacaciones', to='fondos.docente')),
            ],
            options={
                'verbose_name': 'Saldo de Vacaciones',
                'verbose_name_plural': 'Saldos de Vacaciones',
                'ordering': ['-gestion', 'docente'],
                'unique_together': {('docente', 'gestion')},
            },
        ),
    ]
