# Generated by Django 5.2.7 on 2026-03-27 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0033_perfilusuario_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='perfilusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'director')), fields=('carrera', 'rol'), name='unico_director_por_carrera'),
        ),
        migrations.AddConstraint(
            model_name='perfilusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'jefe_estudios')), fields=('carrera', 'rol'), name='unico_jefe_por_carrera'),
        ),
    ]
