# Generated by Django 5.2.7 on 2026-03-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0034_perfilusuario_unico_director_por_carrera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='ci',
        ),
    ]
