# Generated by Django 5.2.7 on 2026-03-30 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0037_alter_perfilusuario_unique_cargos_activos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='perfilusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('rol', 'admin')), fields=('carrera', 'rol'), name='unico_admin_por_carrera'),
        ),
    ]
