# Generated by Django 5.2.7 on 2026-03-31 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0038_perfilusuario_unico_admin_por_carrera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialfondo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='elaborado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_elaborados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajeobservacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_observacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
