# Generated by Django 5.2.7 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0043_carrera_logo_cifrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='mision',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='carrera',
            name='vision',
            field=models.TextField(blank=True, default=''),
        ),
    ]
