# Generated by Django 5.2.7 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0044_carrera_mision_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='perfil_profesional',
            field=models.TextField(blank=True, default='', help_text='Descripción del perfil profesional del egresado'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='objetivo_carrera',
            field=models.TextField(blank=True, default='', help_text='Objetivo general de la carrera'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='responsable',
            field=models.CharField(blank=True, default='', help_text='Nombre/cargo del responsable de la carrera', max_length=200),
        ),
        migrations.AddField(
            model_name='carrera',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
