# Generated by Django 5.2.7 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0045_carrera_campos_nuevos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='fecha_resolucion',
            field=models.DateField(blank=True, help_text='Fecha oficial de la resolución ministerial o universitaria', null=True),
        ),
        migrations.AddField(
            model_name='carrera',
            name='resolucion_ministerial',
            field=models.CharField(blank=True, default='', help_text='Número/código de la resolución ministerial o universitaria que respalda la carrera', max_length=255),
        ),
    ]
