# Generated by Django 5.2.7 on 2026-04-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0046_carrera_resolucion_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cargahoraria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cargahoraria',
            name='titulo_actividad',
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='aula',
            field=models.CharField(default='SIN-AULA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='dia_semana',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado')], default='lunes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='hora_fin',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='hora_inicio',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='Materia del plan de estudios asignada al docente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_horarias', to='fondos.materia'),
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='paralelo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='cargahoraria',
            unique_together={('docente', 'calendario', 'materia', 'paralelo', 'dia_semana', 'hora_inicio')},
        ),
    ]
