# Generated by Django 5.2.7 on 2026-04-05 04:50

import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0048_cargahoraria_cierre_acero_integridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCarrera',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('facultad', models.CharField(choices=[('Facultad de Ciencias y Tecnologia', 'Facultad de Ciencias y Tecnologia'), ('Facultad de Ciencias de la Salud', 'Facultad de Ciencias de la Salud'), ('Facultad de Ciencias Juridicas, Politicas y Sociales', 'Facultad de Ciencias Juridicas, Politicas y Sociales'), ('Facultad de Ciencias Economicas y Financieras', 'Facultad de Ciencias Economicas y Financieras'), ('Facultad de Humanidades y Ciencias de la Educacion', 'Facultad de Humanidades y Ciencias de la Educacion'), ('Facultad de Ciencias Agropecuarias', 'Facultad de Ciencias Agropecuarias')], max_length=200)),
                ('mision', models.TextField(blank=True, default='')),
                ('vision', models.TextField(blank=True, default='')),
                ('perfil_profesional', models.TextField(blank=True, default='', help_text='Descripción del perfil profesional del egresado')),
                ('objetivo_carrera', models.TextField(blank=True, default='', help_text='Objetivo general de la carrera')),
                ('responsable', models.CharField(blank=True, default='', help_text='Nombre/cargo del responsable de la carrera', max_length=200)),
                ('resolucion_ministerial', models.CharField(blank=True, default='', help_text='Número/código de la resolución ministerial o universitaria que respalda la carrera', max_length=255)),
                ('fecha_resolucion', models.DateField(blank=True, help_text='Fecha oficial de la resolución ministerial o universitaria', null=True)),
                ('logo_carrera', models.TextField(blank=True, max_length=100, null=True)),
                ('logo_carrera_cifrada', models.BinaryField(blank=True, null=True)),
                ('logo_carrera_mime', models.CharField(blank=True, default='', max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Carrera',
                'verbose_name_plural': 'historical Carreras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='facultad',
            field=models.CharField(choices=[('Facultad de Ciencias y Tecnologia', 'Facultad de Ciencias y Tecnologia'), ('Facultad de Ciencias de la Salud', 'Facultad de Ciencias de la Salud'), ('Facultad de Ciencias Juridicas, Politicas y Sociales', 'Facultad de Ciencias Juridicas, Politicas y Sociales'), ('Facultad de Ciencias Economicas y Financieras', 'Facultad de Ciencias Economicas y Financieras'), ('Facultad de Humanidades y Ciencias de la Educacion', 'Facultad de Humanidades y Ciencias de la Educacion'), ('Facultad de Ciencias Agropecuarias', 'Facultad de Ciencias Agropecuarias')], max_length=200),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('sigla')), name='materia_sigla_unique_ci_trim'),
        ),
        migrations.AddField(
            model_name='historicalcarrera',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
