# Generated by Django 5.2.7 on 2026-04-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0049_historicalcarrera_alter_carrera_facultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='facultad',
            field=models.CharField(choices=[('Facultad de Ingeniería y Tecnología', 'Facultad de Ingeniería y Tecnología'), ('Facultad de Ciencias y Tecnologia', 'Facultad de Ciencias y Tecnologia'), ('Facultad de Ciencias de la Salud', 'Facultad de Ciencias de la Salud'), ('Facultad de Ciencias Juridicas, Politicas y Sociales', 'Facultad de Ciencias Juridicas, Politicas y Sociales'), ('Facultad de Ciencias Economicas y Financieras', 'Facultad de Ciencias Economicas y Financieras'), ('Facultad de Humanidades y Ciencias de la Educacion', 'Facultad de Humanidades y Ciencias de la Educacion'), ('Facultad de Ciencias Agropecuarias', 'Facultad de Ciencias Agropecuarias')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalcarrera',
            name='facultad',
            field=models.CharField(choices=[('Facultad de Ingeniería y Tecnología', 'Facultad de Ingeniería y Tecnología'), ('Facultad de Ciencias y Tecnologia', 'Facultad de Ciencias y Tecnologia'), ('Facultad de Ciencias de la Salud', 'Facultad de Ciencias de la Salud'), ('Facultad de Ciencias Juridicas, Politicas y Sociales', 'Facultad de Ciencias Juridicas, Politicas y Sociales'), ('Facultad de Ciencias Economicas y Financieras', 'Facultad de Ciencias Economicas y Financieras'), ('Facultad de Humanidades y Ciencias de la Educacion', 'Facultad de Humanidades y Ciencias de la Educacion'), ('Facultad de Ciencias Agropecuarias', 'Facultad de Ciencias Agropecuarias')], max_length=200),
        ),
    ]
