# Generated by Django 5.2.7 on 2026-04-05 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0050_alter_carrera_facultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='historicalcarrera',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='materia',
            name='sigla',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
