# Generated by Django 5.2.7 on 2026-04-05 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0051_alter_carrera_codigo_alter_historicalcarrera_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_usuario', to='fondos.docente'),
        ),
        migrations.CreateModel(
            name='AsignacionCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('director', 'Director de Carrera'), ('jefe_estudios', 'Jefe de Estudios'), ('docente', 'Docente')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_carrera', to='fondos.carrera')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_carrera', to='fondos.docente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_carrera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Carrera',
                'verbose_name_plural': 'Asignaciones de Carrera',
                'constraints': [models.UniqueConstraint(fields=('user', 'carrera', 'rol'), name='uniq_usuario_carrera_rol_asignacion')],
            },
        ),
    ]
