# Generated by Django 5.2.7 on 2026-08-15 11:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0073_fondo_tiempo_anual_40_semanas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarioacademico',
            name='fecha_inicio_presentacion_proyectos',
            field=models.DateField(help_text='Inicio de presentaciÃ³n de proyectos y programas analÃ\xadticos'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='fecha_limite_presentacion_proyectos',
            field=models.DateField(help_text='Fecha lÃ\xadmite para presentar proyectos'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='gestion',
            field=models.IntegerField(help_text='AÃ±o académico', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='fecha_resolucion',
            field=models.DateField(blank=True, help_text='Fecha oficial de la resoluciÃ³n ministerial o universitaria', null=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='resolucion_ministerial',
            field=models.CharField(blank=True, default='', help_text='Número/código de la resoluciÃ³n ministerial o universitaria que respalda la carrera', max_length=255),
        ),
        migrations.AlterField(
            model_name='datoslaborales',
            name='dias_vacacion',
            field=models.IntegerField(default=15, help_text='DÃ\xadas de vacaciÃ³n correspondientes según antigüedad'),
        ),
        migrations.AlterField(
            model_name='datoslaborales',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de ingreso a la institución para cÃ¡lculo de antigüedad'),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que aprobÃ³ el fondo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fondos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='fecha_presentacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de presentaciÃ³n a Director de Carrera', null=True),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='programa_analitico_url',
            field=models.URLField(blank=True, help_text='URL del programa analÃ\xadtico (Google Drive, etc.)'),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='tiene_programa_analitico',
            field=models.BooleanField(default=False, help_text='Indica si se adjuntÃ³ el programa analÃ\xadtico (obligatorio Art. 15)'),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='tipo_fondo',
            field=models.CharField(choices=[('semestral', 'Semestral/Anual'), ('largo_plazo', 'Largo Plazo')], default='semestral', help_text='Define si el fondo es para un periodo académico especÃ\xadfico o a largo plazo.', max_length=20),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='validado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que validÃ³ el fondo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fondos_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcarrera',
            name='fecha_resolucion',
            field=models.DateField(blank=True, help_text='Fecha oficial de la resoluciÃ³n ministerial o universitaria', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcarrera',
            name='resolucion_ministerial',
            field=models.CharField(blank=True, default='', help_text='Número/código de la resoluciÃ³n ministerial o universitaria que respalda la carrera', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True, help_text='Indica si el usuario debe cambiar su contraseÃ±a en el prÃ³ximo inicio de sesiÃ³n'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='justificacion',
            field=models.TextField(help_text='JustificaciÃ³n del proyecto (Art. 16)'),
        ),
        migrations.AlterField(
            model_name='saldovacacionesgestion',
            name='dias_disponibles',
            field=models.IntegerField(help_text='DÃ\xadas de vacaciÃ³n disponibles para esta gestión'),
        ),
        migrations.AlterField(
            model_name='saldovacacionesgestion',
            name='gestion',
            field=models.IntegerField(help_text='AÃ±o/Gestión académica', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
