# Generated by Django 5.2.7 on 2026-08-15 12:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0074_alter_calendarioacademico_fecha_inicio_presentacion_proyectos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubActividadDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preparacion_temas', 'Preparación de temas'), ('clases_aula', 'Clases en aula'), ('elaboracion_tp', 'Elaboración de Trabajos Prácticos'), ('revision_tp', 'Revisión y Calificación de Trabajos Prácticos'), ('elaboracion_examenes', 'Elaboración de Exámenes'), ('revision_examenes', 'Revisión y Calificación de Exámenes'), ('consultas_reclamos', 'Consultas y Reclamos de Calificaciones'), ('planillas_notas', 'Elaboración de planillas e Introducción de notas'), ('planificacion_extra_aula', 'Planificación y gestión de práctica extra aula'), ('ejecucion_extra_aula', 'Ejecución de práctica extra aula'), ('descargo_viaje', 'Informe de descargo de viaje en prácticas'), ('laboratorios', 'Práctica de Laboratorios'), ('campo', 'Prácticas de Campo'), ('produccion_docente', 'Producción docente (textos guías)'), ('cursos_verano', 'Cursos de verano')], max_length=40)),
                ('horas_semana', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('horas_anio', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('evidencias', models.TextField(blank=True, default='')),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fondo_tiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subactividades_docente', to='fondos.fondotiempo')),
            ],
            options={
                'verbose_name': 'Sub-actividad docente',
                'verbose_name_plural': 'Sub-actividades docentes',
                'ordering': ['fondo_tiempo', 'orden', 'id'],
                'unique_together': {('fondo_tiempo', 'tipo')},
            },
        ),
    ]
