# Generated by Django 5.2.7 on 2026-08-17 21:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0075_subactividaddocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefondo',
            name='estado',
            field=models.CharField(choices=[('presentado', 'Presentado'), ('evaluado_director', 'Evaluado por Director'), ('finalizado', 'Finalizado')], default='presentado', max_length=20),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('presentado_jefe', 'En Revision (Jefatura de Estudios)'), ('observado', 'Con Observaciones'), ('presentado_director', 'En Revision (Jefatura de Estudios)'), ('aprobado_director', 'Aprobado (Direccion de Carrera)'), ('en_ejecucion', 'En Ejecución'), ('informe_presentado', 'Informe Presentado'), ('informe_evaluado', 'Informe Evaluado por Director'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado'), ('archivado', 'Archivado')], default='borrador', max_length=30),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='actividades_realizadas',
            field=models.TextField(blank=True, default='', help_text='Detalle de actividades ejecutadas'),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='logros',
            field=models.TextField(blank=True, default='', help_text='Logros alcanzados'),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='resultados',
            field=models.TextField(blank=True, default='', help_text='Resultados obtenidos'),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='resumen_ejecutivo',
            field=models.TextField(blank=True, default='', help_text='Resumen de las actividades realizadas'),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('academica', 'Académica'), ('investigacion', 'Investigación'), ('extension_universitaria', 'Extensión universitaria'), ('interaccion_social', 'Interacción social'), ('gestion', 'Gestión'), ('academica_administrativa', 'Académica-administrativa'), ('social_cultural_deportiva', 'Social, cultural, deportiva y Otros')], max_length=30)),
                ('descripcion_ejecutado', models.TextField()),
                ('archivo', models.FileField(upload_to='informes_evidencias/')),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_informe', to='fondos.actividad')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_digitales', to='fondos.informefondo')),
            ],
            options={
                'verbose_name': 'Evidencia de informe',
                'verbose_name_plural': 'Evidencias de informe',
                'ordering': ['informe', 'categoria', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InformeAsignaturaEjecutada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('sigla', models.CharField(blank=True, default='', max_length=50)),
                ('paralelo', models.CharField(blank=True, default='', max_length=10)),
                ('horas_aula', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('inscritos', models.PositiveIntegerField(default=0)),
                ('aprobados', models.PositiveIntegerField(default=0)),
                ('reprobados', models.PositiveIntegerField(default=0)),
                ('habilitados', models.PositiveIntegerField(default=0)),
                ('descripcion_evaluacion', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_ejecutadas', to='fondos.informefondo')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informes_ejecutados', to='fondos.materia')),
            ],
            options={
                'verbose_name': 'Asignatura ejecutada en informe',
                'verbose_name_plural': 'Asignaturas ejecutadas en informe',
                'ordering': ['informe', 'sigla', 'nombre', 'paralelo'],
            },
        ),
    ]
