# Generated by Django 4.2.16 on 2026-03-10 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('responsable', models.CharField(max_length=500)),
                ('productos_esperados', models.TextField()),
                ('mes_inicio', models.CharField(max_length=20)),
                ('mes_fin', models.CharField(max_length=20)),
                ('indicador_descripcion', models.TextField(blank=True, null=True)),
                ('indicador_unidad', models.CharField(choices=[('numero', 'Número'), ('porcentaje', 'Porcentaje')], default='numero', max_length=50)),
                ('indicador_linea_base', models.IntegerField()),
                ('indicador_meta', models.IntegerField()),
                ('monto_funcion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_inversion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('ejecutado', 'Ejecutado'), ('suspendido', 'Suspendido')], default='programado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField(verbose_name='Año de Gestión')),
                ('unidad_solicitante', models.CharField(max_length=200)),
                ('programa', models.CharField(max_length=200)),
                ('objetivo_gestion_institucional', models.TextField()),
                ('fecha_elaboracion', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='poa_document.documentopoa')),
            ],
        ),
        migrations.AddField(
            model_name='documentopoa',
            name='elaborado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_elaborados', to='poa_document.persona'),
        ),
        migrations.AddField(
            model_name='documentopoa',
            name='jefe_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_jefe', to='poa_document.persona'),
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('funcion', 'Funcionamiento'), ('funcionamiento', 'Funcionamiento'), ('inversion', 'Inversión')], db_index=True, default='funcion', max_length=20)),
                ('partida', models.CharField(db_index=True, max_length=50)),
                ('item', models.CharField(max_length=150)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('caracteristicas', models.TextField(blank=True)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mes_requerimiento', models.CharField(max_length=50)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_presupuesto', to='poa_document.actividad')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='poa_document.objetivoespecifico'),
        ),
        migrations.AlterUniqueTogether(
            name='documentopoa',
            unique_together={('gestion', 'unidad_solicitante', 'programa')},
        ),
    ]
