# Generated by Django 5.2.6 on 2026-03-11 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0028_docente_fecha_ingreso'),
        ('poa_document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('elaborador', 'Elaborador del POA'), ('director_carrera', 'Director de Carrera'), ('revisor_1', 'Entidad Revisora 1'), ('revisor_2', 'Entidad Revisora 2'), ('revisor_3', 'Entidad Revisora 3'), ('revisor_4', 'Entidad Revisora 4')], max_length=30, verbose_name='Rol POA')),
                ('nombre_entidad', models.CharField(blank=True, help_text='Para roles de revisor: nombre de la entidad revisora (ej. DAF, VRA)', max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_poa', to='fondos.docente', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Usuario POA',
                'verbose_name_plural': 'Usuarios POA',
                'ordering': ['rol', 'docente__apellido_paterno'],
                'unique_together': {('docente', 'rol')},
            },
        ),
    ]
