# Generated by Django 5.2.6 on 2026-03-11 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0002_add_usuario_poa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopoa',
            name='elaborado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_elaborados', to='poa_document.usuariopoa'),
        ),
        migrations.AlterField(
            model_name='documentopoa',
            name='jefe_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_jefe', to='poa_document.usuariopoa'),
        ),
        # No-op: `Persona` ya no existe en el estado base actual de la app.
    ]
