# Generated by Django 5.2.6 on 2026-03-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0003_remove_persona_use_usuario_poa'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopoa',
            name='estado',
            field=models.CharField(choices=[('elaboracion', 'En elaboración'), ('revision', 'En revisión'), ('aprobado', 'Aprobado'), ('ejecucion', 'En ejecución')], default='elaboracion', max_length=20, verbose_name='Estado'),
        ),
    ]
